### ISSUE TITLE
Problem displaying an image in the `instruments` section

### ISSUE THREAD

**Issue by blackgolyb** [ulyagram77/ulyagram77.github.io#5]
### Issue description

Problem displaying an image in the `instruments` section

![photo of the problem](https://github.com/ulyagram77/ThreeJS-Landing-React/assets/61083295/c00e8bb9-2925-4e3d-aa76-a1de46f32d63)

### Browser

Mozilla Firefox 122.0

**Comment by ulyagram77** [comment]
Дякую) спробую виправити брате)
